replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/{{ .Values.projectID }}/timer/timer
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 30037

containerPort: 3000

namespace: timer-prod-env
projectID: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
