replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/{{ .Values.projectID }}/timer/timer
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 30036

containerPort: 3000

namespace: timer-prod-env
projectID: ""
