replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/{{ .Values.projectID }}/timer/timer
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  nodePort: null 

containerPort: 3000

namespace: timer-prod-env
projectID: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  host: ""  
  path: /
  pathType: ImplementationSpecific
  tls: []
