apiVersion: v1
kind: Service
metadata:
  name: timer-service
  namespace: timer-prod-env
spec:
  selector:
    app: timer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
