apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  namespace: {{ .Values.namespace }}
  labels:
    app: timer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: timer
  template:
    metadata:
      labels:
        app: timer
    spec:
      containers:
      - name: timer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
