apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
