name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Decode GCP Service Account Key
        run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcp-key.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: $HOME/gcp-key.json

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: docker buildx build --push --tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/timer/timer:latest .

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode GCP Service Account Key
        run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcp-key.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: $HOME/gcp-key.json

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials production --region us-central1 --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: helm upgrade --install timer helm/timer --namespace timer-prod-env
